FROM golang:1.25.1-bookworm AS tools
ENV GOBIN=/out CGO_ENABLED=0
RUN go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@v2.8.0 \
 && go install github.com/projectdiscovery/httpx/cmd/httpx@v1.7.1 \
 && go install github.com/projectdiscovery/katana/cmd/katana@v1.2.1 \
 && go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.4.10 \
 && go install github.com/ffuf/ffuf/v2@v2.1.0

FROM python:3.13.7-slim@sha256:7e5c53e40a443db2c5ce67737f14d97f864f01b8f6d52bf020733be6e016c447
RUN groupadd -r secure && useradd -r -g secure -d /app secure
COPY --from=tools /out/ /usr/local/bin/
WORKDIR /app
COPY pyproject.toml README.md ./
COPY secure ./secure
COPY config ./config
RUN pip install --no-cache-dir . && mkdir -p /data/scans && chown -R secure:secure /data/scans /app
USER secure
