import { useMemo, useState } from "react";
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowSquareOut, CaretDown, CaretRight, Check, CheckCircle, ClockCounterClockwise, Copy, Crosshair, FileText, Funnel, GlobeHemisphereWest, Info, ListMagnifyingGlass, MagnifyingGlass, Play, ShieldCheck, Stop, Warning, X } from "@phosphor-icons/react";

const findings = [
  { id:"f-001", severity:"high", title:"Exposed admin endpoint", summary:"Administrative interface publicly accessible without authentication.", url:"https://example.com/admin", category:"Access control", status:"Needs review", source:"ZAP", rule:"10028", confidence:"High", cwe:"CWE-284", observed:"The scanner received HTTP 200 from /admin and identified an administrative login interface.", impact:"An exposed administrative surface increases the chance of credential attacks and exploitation of known product vulnerabilities.", remediation:"Restrict access using your identity provider, VPN, or an IP allowlist. Remove the endpoint from public access if it is not required.", evidence:"GET /admin HTTP/1.1\nHost: example.com\n\nHTTP/1.1 200 OK\nContent-Type: text/html\nServer: nginx" },
  { id:"f-002", severity:"medium", title:"Missing Content Security Policy", summary:"No Content-Security-Policy response header was detected.", url:"https://example.com", category:"Security headers", status:"Needs review", source:"ZAP + Nuclei", rule:"10038", confidence:"High", cwe:"CWE-693", observed:"Responses did not include a Content-Security-Policy header.", impact:"Without a CSP, injected browser content has fewer restrictions and some cross-site scripting attacks may have greater impact.", remediation:"Start with a report-only policy, review violations, then enforce a restrictive policy tailored to the application.", evidence:"HTTP/1.1 200 OK\nContent-Type: text/html\nX-Frame-Options: SAMEORIGIN\n\nContent-Security-Policy: <not present>" },
  { id:"f-003", severity:"medium", title:"Server version disclosed", summary:"Web server version information is disclosed in response headers.", url:"https://example.com", category:"Information disclosure", status:"Open", source:"ZAP", rule:"10036", confidence:"High", cwe:"CWE-200", observed:"The Server response header includes a precise product version.", impact:"Version disclosure helps attackers narrow their search for relevant vulnerabilities.", remediation:"Configure the web server or reverse proxy to suppress detailed version information.", evidence:"Server: nginx/1.24.0" },
  { id:"f-004", severity:"low", title:"Cookie missing Secure attribute", summary:"A session cookie may be sent over an unencrypted connection.", url:"https://example.com/account", category:"Session management", status:"Open", source:"ZAP", rule:"10011", confidence:"Medium", cwe:"CWE-614", observed:"The session cookie was set without the Secure attribute.", impact:"The cookie could be exposed if a browser is ever directed to an insecure origin.", remediation:"Set Secure, HttpOnly, and an appropriate SameSite policy on session cookies.", evidence:"Set-Cookie: session=…; Path=/; HttpOnly" },
  { id:"f-005", severity:"low", title:"Directory listing enabled", summary:"Directory contents are exposed under /uploads/.", url:"https://example.com/uploads/", category:"Configuration", status:"Open", source:"Nuclei", rule:"directory-listing", confidence:"Medium", cwe:"CWE-548", observed:"A directory index page was returned for /uploads/.", impact:"Public listings can expose forgotten files, backups, or internal naming conventions.", remediation:"Disable directory indexing and publish only files intended for direct public access.", evidence:"<title>Index of /uploads/</title>" },
];

function Logo(){return <Link to="/" className="brand" aria-label="Secure home"><ShieldCheck weight="duotone" size={30}/><span>SECURE</span></Link>}
function Shell({children}){return <div className="app-shell"><aside className="sidebar"><Logo/><nav aria-label="Primary navigation"><NavLink to="/" end><Crosshair size={20}/><span>Scan</span></NavLink><NavLink to="/history"><ClockCounterClockwise size={20}/><span>History</span></NavLink><NavLink to="/targets"><GlobeHemisphereWest size={20}/><span>Targets</span></NavLink></nav><div className="sidebar-note"><span className="status-dot"/>Systems operational</div></aside><div className="workspace"><header className="topbar"><div><strong>Operations Console</strong><span>Authorized web security scanning</span></div><div className="ready"><span className="status-dot"/>Scanner ready</div></header>{children}</div></div>}
function Severity({level}){return <span className={`severity severity-${level}`}>{level}</span>}

function ScanPage(){
  const navigate=useNavigate(); const [target,setTarget]=useState("https://example.com"); const [authorized,setAuthorized]=useState(true); const [running,setRunning]=useState(true); const [query,setQuery]=useState(""); const [severity,setSeverity]=useState("all");
  const visible=useMemo(()=>findings.filter(item=>`${item.title} ${item.summary} ${item.url}`.toLowerCase().includes(query.toLowerCase())&&(severity==="all"||item.severity===severity)),[query,severity]);
  const startScan=e=>{e.preventDefault();if(authorized&&target)setRunning(true)};
  return <Shell><main className="content" id="main-content">
    <section className="page-heading"><div><p className="eyebrow">Authorized assessment</p><h1>Quick Scan</h1><p>Map the exposed web surface, collect scanner signals, and produce one understandable report.</p></div><a href="#guidelines">Scanning guidelines <ArrowSquareOut size={16}/></a></section>
    <form className="scan-form" onSubmit={startScan}><label htmlFor="target">Target URL</label><div className="target-control"><GlobeHemisphereWest size={20}/><input id="target" value={target} onChange={e=>setTarget(e.target.value)} spellCheck="false"/></div><button className="profile-button" type="button">Quick Scan <CaretDown size={15}/></button><button className="primary-button" type="submit" disabled={!authorized||!target}><Play weight="fill" size={17}/>Start scan</button><label className="authorization"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/><span><Check size={12} weight="bold"/></span>I confirm I am authorized to scan this target.</label></form>
    <section className="progress-panel" aria-live="polite"><div className="panel-heading"><div><h2>{running?"Scanning":"Scan paused"} <code>{target}</code></h2><p>Quick Scan <span>•</span> Started 10:42:17 <span>•</span> Elapsed 02:34</p></div><button className="secondary-button" onClick={()=>setRunning(v=>!v)}>{running?<><Stop weight="fill" size={14}/>Cancel scan</>:<><Play weight="fill" size={14}/>Resume demo</>}</button></div><ol className="stepper"><li className="complete"><span><Check size={16} weight="bold"/></span><strong>Discover assets</strong><small>14 assets found</small></li><li className="complete"><span><Check size={16} weight="bold"/></span><strong>Probe live sites</strong><small>7 responding</small></li><li className={running?"active":""}><span>3</span><strong>Crawl endpoints</strong><small>{running?"In progress":"Paused"}</small></li><li><span>4</span><strong>Security analysis</strong><small>Pending</small></li><li><span>5</span><strong>Generate report</strong><small>Pending</small></li></ol></section>
    <section className="metrics" aria-label="Scan summary"><div><GlobeHemisphereWest size={22}/><span>Assets<strong>14</strong></span></div><div><FileText size={22}/><span>Endpoints<strong>243</strong></span></div><div><Warning size={22}/><span>High<strong>2</strong></span></div><div><Warning size={22}/><span>Medium<strong>5</strong></span></div><div><Info size={22}/><span>Low<strong>12</strong></span></div></section>
    <section className="findings-panel"><div className="findings-toolbar"><div><h2>Findings</h2><span className="count">{visible.length}</span></div><div className="filters"><label className="select-wrap"><Funnel size={16}/><span className="sr-only">Filter by severity</span><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><CaretDown size={14}/></label><label className="search-wrap"><MagnifyingGlass size={17}/><span className="sr-only">Search findings</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search findings"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear search"><X size={14}/></button>}</label></div></div><div className="table-scroll"><table><thead><tr><th>#</th><th>Severity</th><th>Finding</th><th>Affected resource</th><th>Category</th><th>Status</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{visible.map((item,index)=><tr key={item.id} tabIndex="0" onClick={()=>navigate(`/findings/${item.id}`)} onKeyDown={e=>{if(e.key==="Enter")navigate(`/findings/${item.id}`)}}><td>{index+1}</td><td><Severity level={item.severity}/></td><td><strong>{item.title}</strong><small>{item.summary}</small></td><td><code>{item.url}</code></td><td>{item.category}</td><td><span className="status-pill">{item.status}</span></td><td><CaretRight size={17}/></td></tr>)}</tbody></table></div>{!visible.length&&<div className="empty-state"><ListMagnifyingGlass size={34}/><h3>No findings match</h3><p>Try another search or severity filter.</p></div>}</section>
  </main></Shell>
}

function FindingDetail(){
  const {id}=useParams(); const navigate=useNavigate(); const item=findings.find(f=>f.id===id)||findings[0]; const [copied,setCopied]=useState(false);
  const copyEvidence=async()=>{await navigator.clipboard?.writeText(item.evidence);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
  return <Shell><main className="content detail-content"><button className="back-button" onClick={()=>navigate(-1)}><ArrowLeft size={18}/>Back to findings</button><header className="detail-header"><div><div className="detail-kicker"><Severity level={item.severity}/><span>{item.status}</span></div><h1>{item.title}</h1><code>{item.url}</code></div><button className="secondary-button">Mark as reviewed</button></header><section className="detail-grid"><article className="detail-main"><section><h2>What was observed</h2><p>{item.observed}</p></section><section><h2>Why it matters</h2><p>{item.impact}</p></section><section><div className="section-title-row"><h2>Evidence</h2><button onClick={copyEvidence}>{copied?<CheckCircle size={16}/>:<Copy size={16}/>} {copied?"Copied":"Copy"}</button></div><pre>{item.evidence}</pre></section><section className="remediation"><h2>Suggested remediation</h2><p>{item.remediation}</p></section></article><aside className="finding-meta"><h2>Finding details</h2><dl><div><dt>Source scanner</dt><dd>{item.source}</dd></div><div><dt>Rule ID</dt><dd><code>{item.rule}</code></dd></div><div><dt>Confidence</dt><dd>{item.confidence}</dd></div><div><dt>CWE</dt><dd><a href={`https://cwe.mitre.org/data/definitions/${item.cwe.split("-")[1]}.html`}>{item.cwe}<ArrowSquareOut size={13}/></a></dd></div><div><dt>Category</dt><dd>{item.category}</dd></div></dl><p className="signal-note"><Info size={18}/>This is an automated signal. Review the evidence before treating it as a confirmed vulnerability.</p></aside></section></main></Shell>
}
function Placeholder({title}){return <Shell><main className="content placeholder-page"><p className="eyebrow">Secure</p><h1>{title}</h1><p>This section is prepared for the next product milestone.</p><Link to="/">Return to Quick Scan</Link></main></Shell>}
export function App(){return <BrowserRouter><a className="skip-link" href="#main-content">Skip to content</a><Routes><Route path="/" element={<ScanPage/>}/><Route path="/findings/:id" element={<FindingDetail/>}/><Route path="/history" element={<Placeholder title="Scan history"/>}/><Route path="/targets" element={<Placeholder title="Authorized targets"/>}/></Routes></BrowserRouter>}
