import { useState } from "react";
import { BrowserRouter, Link, NavLink, Route, Routes } from "react-router-dom";
import { ArrowRight, CaretDown, Check, ClockCounterClockwise, Crosshair, Funnel, GlobeHemisphereWest, Info, ListMagnifyingGlass, MagnifyingGlass, Play, ShieldCheck, SignOut, UserCircle, X } from "@phosphor-icons/react";

const WORKSPACE_KEY = "secure.workspace";
function loadWorkspace(){try{return JSON.parse(window.localStorage.getItem(WORKSPACE_KEY))||null}catch{return null}}
function Logo(){return <Link to="/" className="brand" aria-label="Secure home"><ShieldCheck weight="duotone" size={30}/><span>SECURE</span></Link>}
function AccountButton({workspace,onReset}){const initials=workspace.owner.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase();return <details className="account-menu"><summary><span className="avatar">{initials}</span><span><strong>{workspace.owner}</strong><small>{workspace.organization}</small></span><CaretDown size={14}/></summary><div className="account-popover"><div><UserCircle size={18}/><span><strong>{workspace.email}</strong><small>Workspace owner</small></span></div><button onClick={onReset}><SignOut size={17}/>Reset workspace</button></div></details>}
function Shell({children,workspace,onReset}){return <div className="app-shell"><aside className="sidebar"><Logo/><nav aria-label="Primary navigation"><NavLink to="/" end><Crosshair size={20}/><span>Scan</span></NavLink><NavLink to="/history"><ClockCounterClockwise size={20}/><span>History</span></NavLink><NavLink to="/targets"><GlobeHemisphereWest size={20}/><span>Targets</span></NavLink></nav><div className="sidebar-note"><span className="status-dot"/>Workspace ready</div></aside><div className="workspace"><header className="topbar"><div><strong>{workspace.organization}</strong><span>Security operations workspace</span></div><AccountButton workspace={workspace} onReset={onReset}/></header>{children}</div></div>}

function SetupPage({onComplete}){
  const [step,setStep]=useState(1);const [form,setForm]=useState({owner:"",email:"",organization:"",target:"",authorized:false});const [error,setError]=useState("");
  const update=(field,value)=>setForm(current=>({...current,[field]:value}));
  const accountReady=form.owner.trim()&&/^\S+@\S+\.\S+$/.test(form.email)&&form.organization.trim();
  const targetReady=(()=>{try{const url=new URL(form.target);return url.protocol==="https:"&&Boolean(url.hostname)&&form.authorized}catch{return false}})();
  const submit=e=>{e.preventDefault();setError("");if(step===1){if(!accountReady){setError("Complete each account field to continue.");return}setStep(2);return}if(!targetReady){setError("Enter a valid HTTPS target and confirm authorization.");return}onComplete({...form,owner:form.owner.trim(),email:form.email.trim(),organization:form.organization.trim(),target:form.target.trim()})};
  return <main className="setup-shell"><section className="setup-intro"><Logo/><div><p className="eyebrow">Permission-based security assessment</p><h1>Know what your business exposes.</h1><p>Set up a private workspace for your organization, authorize your first web property, and review scanner evidence in one place.</p></div><ul><li><span><Check size={15} weight="bold"/></span>Low-impact quick scans</li><li><span><Check size={15} weight="bold"/></span>Evidence grouped by finding</li><li><span><Check size={15} weight="bold"/></span>Clear remediation guidance</li></ul><p className="setup-footnote">Automated observations are signals, not a penetration-test certification.</p></section><section className="setup-form-panel"><div className="setup-progress"><span className={step>=1?"active":""}>1</span><i/><span className={step>=2?"active":""}>2</span><div><small>Account</small><small>First target</small></div></div><div className="setup-copy"><p className="eyebrow">Step {step} of 2</p><h2>{step===1?"Create your workspace":"Authorize your first target"}</h2><p>{step===1?"This information identifies the operator responsible for scans.":"Only add a web property your organization is permitted to assess."}</p></div><form className="setup-form" onSubmit={submit}>{step===1?<><label>Full name<input autoFocus autoComplete="name" value={form.owner} onChange={e=>update("owner",e.target.value)}/></label><label>Work email<input type="email" autoComplete="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label>Organization<input autoComplete="organization" value={form.organization} onChange={e=>update("organization",e.target.value)}/></label></>:<><label>Authorized target<input autoFocus inputMode="url" spellCheck="false" aria-describedby="target-help" value={form.target} onChange={e=>update("target",e.target.value)}/></label><p id="target-help" className="field-help">Use the HTTPS address of the public web application you control.</p><label className="consent-card"><input type="checkbox" checked={form.authorized} onChange={e=>update("authorized",e.target.checked)}/><span><Check size={13} weight="bold"/></span><span><strong>I have authority to scan this target</strong><small>The authorization record will be attached to scans started from this workspace.</small></span></label></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="setup-actions">{step===2&&<button type="button" className="text-button" onClick={()=>{setError("");setStep(1)}}>Back</button>}<button className="primary-button" type="submit">{step===1?"Continue":"Finish setup"}<ArrowRight size={17}/></button></div></form><p className="storage-note"><Info size={15}/>Setup is stored in this browser for this frontend deployment.</p></section></main>
}

function EmptyFindings(){return <div className="empty-state"><div className="empty-icon"><ListMagnifyingGlass size={28}/></div><h3>No findings yet</h3><p>Run the first authorized scan to populate this table with real scanner results.</p></div>}
function ScanPage({workspace,onReset}){const [target,setTarget]=useState(workspace.target||"");const [authorized,setAuthorized]=useState(false);const [notice,setNotice]=useState("");const start=e=>{e.preventDefault();setNotice("The workspace is configured. Connect this frontend to the Secure API to start live scans.")};return <Shell workspace={workspace} onReset={onReset}><main className="content" id="main-content"><section className="page-heading"><div><p className="eyebrow">Authorized assessment</p><h1>Quick Scan</h1><p>Review the target and authorization record before starting a low-impact assessment.</p></div><div className="account-status"><span className="status-dot"/><span><strong>Setup complete</strong><small>1 authorized target</small></span></div></section><form className="scan-form" onSubmit={start}><label htmlFor="target">Target URL</label><div className="target-control"><GlobeHemisphereWest size={20}/><input id="target" value={target} onChange={e=>setTarget(e.target.value)} spellCheck="false"/></div><button className="profile-button" type="button">Quick Scan <CaretDown size={15}/></button><button className="primary-button" type="submit" disabled={!authorized||!target}><Play weight="fill" size={17}/>Start scan</button><label className="authorization"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/><span><Check size={12} weight="bold"/></span>I confirm I am authorized to scan this target.</label></form>{notice&&<div className="integration-notice" role="status"><Info size={18}/><span>{notice}</span><button onClick={()=>setNotice("")} aria-label="Dismiss"><X size={15}/></button></div>}<section className="empty-overview"><div><span className="empty-overview-icon"><ShieldCheck size={27}/></span><div><p className="eyebrow">Ready for first scan</p><h2>No assessment data yet</h2><p>Metrics and scan progress appear here only after the backend accepts a real scan.</p></div></div><dl><div><dt>Assets</dt><dd>—</dd></div><div><dt>Endpoints</dt><dd>—</dd></div><div><dt>High</dt><dd>—</dd></div><div><dt>Medium</dt><dd>—</dd></div><div><dt>Low</dt><dd>—</dd></div></dl></section><section className="findings-panel"><div className="findings-toolbar"><div><h2>Findings</h2><span className="count">0</span></div><div className="filters"><label className="select-wrap disabled-control"><Funnel size={16}/><span className="sr-only">Filter by severity</span><select disabled><option>All severities</option></select><CaretDown size={14}/></label><label className="search-wrap disabled-control"><MagnifyingGlass size={17}/><span className="sr-only">Search findings</span><input disabled aria-label="Search findings"/></label></div></div><div className="table-scroll"><table><thead><tr><th>#</th><th>Severity</th><th>Finding</th><th>Affected resource</th><th>Category</th><th>Status</th><th/></tr></thead></table></div><EmptyFindings/></section></main></Shell>}
function HistoryPage({workspace,onReset}){return <Shell workspace={workspace} onReset={onReset}><main className="content collection-page" id="main-content"><section className="page-heading"><div><p className="eyebrow">Assessment records</p><h1>Scan history</h1><p>Completed, partial, cancelled, and failed assessments will appear here.</p></div></section><section className="collection-empty"><ClockCounterClockwise size={30}/><h2>No scans recorded</h2><p>Your organization has not started an assessment from this workspace.</p><Link className="primary-button" to="/">Start with Quick Scan</Link></section></main></Shell>}
function TargetsPage({workspace,onReset}){return <Shell workspace={workspace} onReset={onReset}><main className="content collection-page" id="main-content"><section className="page-heading"><div><p className="eyebrow">Assessment scope</p><h1>Authorized targets</h1><p>Only approved customer assets should be available to scanner workers.</p></div></section><section className="target-card"><div className="target-mark"><GlobeHemisphereWest size={22}/></div><div><code>{workspace.target}</code><p>Added during workspace setup</p></div><span className="status-pill">Attended consent</span></section></main></Shell>}
function Product(){const [workspace,setWorkspace]=useState(loadWorkspace);const complete=value=>{window.localStorage.setItem(WORKSPACE_KEY,JSON.stringify(value));setWorkspace(value)};const reset=()=>{window.localStorage.removeItem(WORKSPACE_KEY);setWorkspace(null)};if(!workspace)return <SetupPage onComplete={complete}/>;return <><a className="skip-link" href="#main-content">Skip to content</a><Routes><Route path="/" element={<ScanPage workspace={workspace} onReset={reset}/>}/><Route path="/history" element={<HistoryPage workspace={workspace} onReset={reset}/>}/><Route path="/targets" element={<TargetsPage workspace={workspace} onReset={reset}/>}/><Route path="*" element={<ScanPage workspace={workspace} onReset={reset}/>}/></Routes></>}
export function App(){return <BrowserRouter><Product/></BrowserRouter>}
